const AppError = require('../../utils/AppError');
const { isUuid } = require('../../utils/validators');
const { writeAudit } = require('../../utils/audit');
const chatRepository = require('./chat.repository');

function buildDisplayName(profile, email) {
  if (!profile) {
    return email;
  }

  return [profile.nombres, profile.apellidos].filter(Boolean).join(' ') || email;
}

async function resolveUserContext(userId) {
  const user = await chatRepository.findUserById(userId);
  if (!user) {
    throw new AppError('User not found', 404);
  }

  const profile = await chatRepository.findDisplayProfile(userId);
  return {
    ...user,
    displayName: buildDisplayName(profile, user.email)
  };
}

function resolveConversationType(currentRole, targetRole) {
  const normalizedRoles = [currentRole, targetRole].sort().join(':');
  const mapping = {
    'administrador:comisionista': 'admin_gestor',
    'administrador:medico': 'admin_medico',
    'comisionista:medico': 'medico_gestor',
    'comisionista:paciente': 'paciente_gestor'
  };

  return mapping[normalizedRoles] || null;
}

async function ensureConversationPermission(currentUser, targetUser) {
  const conversationType = resolveConversationType(currentUser.role, targetUser.role);

  if (!conversationType) {
    throw new AppError('Users cannot start a conversation with this role combination', 403);
  }

  if (currentUser.role === 'paciente') {
    const linked = await chatRepository.isPatientLinkedToCommissioner(currentUser.id, targetUser.id);
    if (!linked) {
      throw new AppError('Patient cannot contact a gestor outside the assigned scope', 403);
    }
  }

  if (currentUser.role === 'medico') {
    const linked = await chatRepository.isDoctorLinkedToCommissioner(currentUser.id, targetUser.id);
    if (!linked) {
      throw new AppError('Doctor cannot contact a gestor outside the assigned scope', 403);
    }
  }

  if (currentUser.role === 'comisionista' && targetUser.role === 'paciente') {
    const linked = await chatRepository.isPatientLinkedToCommissioner(targetUser.id, currentUser.id);
    if (!linked) {
      throw new AppError('Gestor cannot contact a patient outside the assigned scope', 403);
    }
  }

  if (currentUser.role === 'comisionista' && targetUser.role === 'medico') {
    const linked = await chatRepository.isDoctorLinkedToCommissioner(targetUser.id, currentUser.id);
    if (!linked) {
      throw new AppError('Gestor cannot contact a doctor outside the assigned scope', 403);
    }
  }

  return conversationType;
}

async function listConversations(user, filters = {}) {
  const rows = await chatRepository.listConversationsForUser(user.sub, filters);

  return Promise.all(
    rows.map(async (conversation) => {
      const participants = await chatRepository.listConversationParticipants(conversation.id);
      return {
        ...conversation,
        participants: await Promise.all(
          participants.map(async (participant) => {
            const context = await resolveUserContext(participant.userId);
            return {
              ...participant,
              displayName: context.displayName
            };
          })
        )
      };
    })
  );
}

async function listAvailableContacts(user, filters = {}) {
  const rows = await chatRepository.listAvailableContacts(user.sub, user.role, filters.search || '');

  return rows.map((contact) => ({
    ...contact,
    displayName: contact.displayName || contact.email
  }));
}

async function openConversation(payload, user) {
  if (!isUuid(payload.counterpartUserId)) {
    throw new AppError('Invalid counterpartUserId', 400);
  }

  if (payload.counterpartUserId === user.sub) {
    throw new AppError('Cannot create a conversation with yourself', 400);
  }

  const currentUser = await resolveUserContext(user.sub);
  const targetUser = await resolveUserContext(payload.counterpartUserId);
  const conversationType = await ensureConversationPermission(currentUser, targetUser);
  const existingConversationId = await chatRepository.findConversationBetweenUsers(
    currentUser.id,
    targetUser.id,
    conversationType
  );

  if (existingConversationId) {
    return getConversation(existingConversationId, user);
  }

  const conversation = await chatRepository.createConversation({
    type: conversationType,
    subject: payload.subject || `Conversacion entre ${currentUser.displayName} y ${targetUser.displayName}`,
    contextType: 'operativo',
    participants: [
      { userId: currentUser.id, role: currentUser.role },
      { userId: targetUser.id, role: targetUser.role }
    ]
  });

  await chatRepository.createMessage(
    conversation.id,
    currentUser.id,
    `Conversacion iniciada por ${currentUser.displayName}.`,
    'sistema',
    { autoGenerated: true }
  );

  await writeAudit({
    actorUserId: user.sub,
    entity: 'conversacion',
    entityId: conversation.id,
    action: 'crear_conversacion',
    newValues: { type: conversationType, counterpartUserId: payload.counterpartUserId }
  });

  return getConversation(conversation.id, user);
}

async function getConversation(conversationId, user) {
  if (!isUuid(conversationId)) {
    throw new AppError('Invalid conversationId', 400);
  }

  const conversation = await chatRepository.getConversationById(conversationId);
  if (!conversation) {
    throw new AppError('Conversation not found', 404);
  }

  const participants = await chatRepository.listConversationParticipants(conversationId);
  if (user.role !== 'administrador' && !participants.some((participant) => participant.userId === user.sub)) {
    throw new AppError('You do not have permission to access this conversation', 403);
  }

  const participantContexts = await Promise.all(
    participants.map(async (participant) => {
      const context = await resolveUserContext(participant.userId);
      return {
        ...participant,
        displayName: context.displayName
      };
    })
  );

  const messages = await chatRepository.listMessages(conversationId);

  return {
    ...conversation,
    participants: participantContexts,
    messages
  };
}

async function sendMessage(conversationId, payload, user) {
  if (!payload.content || !String(payload.content).trim()) {
    throw new AppError('Message content is required', 400);
  }

  const conversation = await getConversation(conversationId, user);
  const isParticipant = conversation.participants.some((participant) => participant.userId === user.sub);

  if (!isParticipant && user.role !== 'administrador') {
    throw new AppError('You do not have permission to send messages in this conversation', 403);
  }

  const message = await chatRepository.createMessage(conversationId, user.sub, String(payload.content).trim(), 'texto');

  await writeAudit({
    actorUserId: user.sub,
    entity: 'mensaje_conversacion',
    entityId: message.id,
    action: 'enviar_mensaje_chat',
    newValues: { conversationId }
  });

  return message;
}

async function markConversationRead(conversationId, user) {
  if (!isUuid(conversationId)) {
    throw new AppError('Invalid conversationId', 400);
  }

  const readReceipt = await chatRepository.markConversationRead(conversationId, user.sub);
  if (!readReceipt) {
    throw new AppError('Conversation not found', 404);
  }

  return readReceipt;
}

module.exports = {
  getConversation,
  listAvailableContacts,
  listConversations,
  markConversationRead,
  openConversation,
  sendMessage
};
